# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ef09dfeac37b6c2234e284d80ac078f905a8d3f192eaaa72f4148a0fbc8f42e466b265367bcd8835311970385b5e8d9f708072de277e92f171c893339c2880

test:
  secret_key_base: 11ed4321f0d3d130ea1405bf9c148cc73cb551d0f5d9df17529e341fdde227a57265075204c18a1cd06f2a4f248683c32662ac1f58a0a2a5313bc11c5b43ae39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
